# config-management.yaml

apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: usercluster1
  git:
    syncRepo: https://github.com/kbhattac/config-management.git
    syncBranch: master
    secretType: none
    policyDir: corp
  configConnector:
    enabled: false
  policyController:
    enabled: true
