apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: journalbeat-dynamic
  namespace: metrics
  labels:
    k8s-app: journalbeat-dynamic
spec:
  selector:
    matchLabels:
      k8s-app: journalbeat-dynamic
  template:
    metadata:
      labels:
        k8s-app: journalbeat-dynamic
    spec:
      serviceAccountName: journalbeat-dynamic
      terminationGracePeriodSeconds: 30
      containers:
        - name: journalbeat-dynamic
          image: docker.elastic.co/beats/journalbeat:7.0.0
          args: ["-c", "/etc/journalbeat.yml", "-e"]
          env:
            - name: ELASTICSEARCH_HOST
              value: 172.16.141.51
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_USERNAME
              value:
            - name: ELASTICSEARCH_PASSWORD
              value:
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/journalbeat.yml
              readOnly: true
              subPath: journalbeat.yml
            - name: data
              mountPath: /usr/share/journalbeat/data
            - name: varlogjournal
              mountPath: /var/log/journal
              readOnly: true
            - name: machineid
              mountPath: /etc/machineid
              readOnly: true
            - name: systemd
              mountPath: /run/systemd
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: journalbeat-dynamic-config
        - name: varlogjournal
          hostPath:
            path: /var/log/journal
        - name: machineid
          hostPath:
            path: /etc/machine-id
        - name: systemd
          hostPath:
            path: /run/systemd
        - name: data
          emptyDir: {}
